config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles, only: [:new, :create, :show] do
    get :like, on: :member
    get :dislike, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  DEFAULT_RATING = 0

  validates_presence_of :created_at
  validates :body, presence: true, allow_blank: false

  def rate! modifier
    update(rating: self.rating + modifier)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  SESSION_VOTED_ARTICLES = :voted_articles

  def index
    sort_by = "created_at"
    sort_by = "rating" if params[:sort_by] == "rating"
    @articles = Article.all.sort{|f, s| s[sort_by] <=> f[sort_by]}
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article["created_at"] = Time.now

    respond_to do |format|
      if @article.save
        format.html { redirect_to root_path}
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def dislike
    rate_for_article(-1, params[:id])
  end

  def like
    rate_for_article(1, params[:id])
  end

  def rate_for_article modifier, article_id
    voted_articles = session[SESSION_VOTED_ARTICLES] || []
    return if voted_articles.include?(article_id)

    @article = Article.find(article_id)
    return if @article.nil?

    @article.rate! modifier
    voted_articles << article_id
    session[SESSION_VOTED_ARTICLES] = voted_articles

    render js: "$('##{article_id}').html('#{@article.rating}')"
  end

  private

  def article_params
    params.require(:article).permit(:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= render 'partials/brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "New", root_path({sort_by: "created_at"}), class: "nav-link"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Best", root_path({sort_by: "rating"}), class: "nav-link" %>
      </li>
    </ul>
    <%= link_to 'Add quote', new_article_path, class: "btn btn-outline-light my-2 my-sm-0" %>
  </div>
</nav>

<% @articles.each do |article| %>
  <blockquote class="blockquote text-center">
    <div class="container">
      <div class="row">
        <div class="col">
          <p >
            Rating: <span id=<%= article.id%> ><%= article.rating %></span>
          </p>
        </div>
        <div class="col-6">
        </div>
        <div class="col">
          <%= link_to "Like", like_article_path(article), remote: true, class: "btn btn-primary"  %>
          <%= link_to "Dislike", dislike_article_path(article), remote: true, class: "btn btn-secondary"  %>
        </div>
      </div>
    </div>
    <p class="mb-0"><%= article.body %></p>
    <footer class="blockquote-footer">Created at: <%= article.created_at.time.to_formatted_s(:long) %></footer>
  </blockquote>
<% end %>

app/views/articles/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= render 'partials/brand' %>
</nav>

<%= form_for @article, url: articles_path, class: "form-inline my-2 my-lg-0", local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <textarea class="form-control" name="article[body]" required type="text"></textarea>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <button class="btn btn-primary" type="submit">Add</button>
    </div>
  </div>

<% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= @article.body %><br>
<%= @article.created_at %><br>
<%= @article.id %><br>

<%= link_to 'Back to articles', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bash</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
<%= yield %>
</body>
</html>

app/views/partials/_brand.html.erb
<%= link_to "MyBash", root_path, class: "navbar-brand" %>